// LocalizationTests.swift
//
// Foundation guard for the Arabic translation rollout. Confirms:
//   • The Localizable.xcstrings catalog ships in the package bundle.
//   • Every key referenced by S.* resolves to a non-empty string in EN.
//   • Key Arabic translations resolve to non-empty strings (and aren't
//     accidentally still in English).
//
// As more keys land in the catalog, add them to `keysToCheck`. This
// is the "20 high-traffic strings" foundation; expanding it is a
// commit per batch of new strings, not a refactor.

import Testing
import Foundation
@testable import RostrPlusFeature

@Suite("Localization foundation")
struct LocalizationTests {

    /// Every key that has both EN + AR coverage in the current catalog.
    /// Mirror this list when adding new entries to Localizable.xcstrings.
    private static let keysToCheck: [String] = [
        "common.back", "common.cancel", "common.save", "common.done", "common.retry",
        "tab.home", "tab.roster", "tab.bookings", "tab.inbox", "tab.me",
        "auth.signin", "auth.signup", "auth.signout", "auth.forgotpassword",
        "cta.book", "cta.message", "cta.share",
        "state.loading", "state.empty.bookings", "state.empty.inbox", "state.offline",
        "epk.title", "calendar.title", "notifications.title"
    ]

    @Test("Catalog ships in the package bundle")
    func catalogShips() {
        // Bundle.module is generated by SPM when a target has resources.
        // If resource processing fails (file missing, JSON malformed)
        // the bundle either won't include the catalog or will throw on
        // access. Pulling a single key proves the round-trip works.
        let value = String(localized: "common.back", bundle: .module)
        #expect(!value.isEmpty)
        #expect(value != "common.back", "Key fell through unlocalised — catalog isn't being read")
    }

    @Test("Every advertised key resolves in English")
    func everyKeyResolvesEN() {
        for key in Self.keysToCheck {
            let value = String(localized: String.LocalizationValue(key), bundle: .module)
            #expect(!value.isEmpty, "Empty EN translation for \(key)")
            #expect(value != key, "Key fell through unlocalised: \(key)")
        }
    }

    @Test("Every advertised key has a distinct Arabic translation")
    func everyKeyTranslatedAR() throws {
        // String(localized:locale:) honours the *bundle's* preferred
        // language list, not the locale parameter, so on a sim running
        // in English it always returns the EN string. Load the ar.lproj
        // sub-bundle directly to test the AR table.
        let arBundle = try #require(
            Bundle.module.path(forResource: "ar", ofType: "lproj")
                .flatMap(Bundle.init(path:)),
            "ar.lproj missing from package bundle — String Catalog isn't compiling Arabic"
        )
        for key in Self.keysToCheck {
            let arValue = arBundle.localizedString(forKey: key, value: nil, table: nil)
            let enValue = Bundle.module.localizedString(forKey: key, value: nil, table: nil)
            #expect(!arValue.isEmpty, "Empty AR translation for \(key)")
            // For our 20 starter keys, the AR translation should differ
            // from the EN. If a future key is intentionally identical
            // (e.g. a brand name like 'ROSTR+'), drop it from this
            // assertion explicitly.
            #expect(arValue != enValue,
                    "AR translation for \(key) is identical to EN — likely missing a translation")
        }
    }
}
